package com.duobiao.mainframedart.network;

import android.content.Context;
import android.text.TextUtils;

import com.alibaba.fastjson.JSON;
import com.duobiao.mainframedart.network.imInterface.ApiCallBack;
import com.duobiao.mainframedart.network.msg.H8FileUploadMessage;
import com.duobiao.mainframedart.network.msg.H8HttpMessage;

import java.util.HashMap;

/**
 * API枚举集合体，负责创建Http消息
 *
 * @author wangfan
 *         位置搜索http://api.map.baidu.com/place/v2/search?output=json&page_num
 *         =0&ak
 *         =gBuOT3LsnEiQgGDpVzahKa3x&location=39.993469%2C116.470038&radius=
 *         2000&query=%E5%B0%8F%E5%8C%BA&page_size=100
 */
public enum EnumTasks {
    ACCOUNT_MOBCODEOPEN(DHMessage.PATH__ACCOUNT_MOBCODEOPEN_, DHMessage.METHOD__ACCOUNT_MOBCODEOPEN_, null),
    ACCOUNT_CHECKOPENMOBILE(DHMessage.PATH__ACCOUNT_CHECKOPENMOBILE_, DHMessage.METHOD__ACCOUNT_CHECKOPENMOBILE_, null),
    ACCOUNT_GETOPENINFO(DHMessage.PATH__ACCOUNT_GETOPENINFO_, DHMessage.METHOD__ACCOUNT_GETOPENINFO_, null),
    WEIXIN_GETUSERINFO("https://api.weixin.qq.com/sns/userinfo", "GET", null),
    WEIXIN_GETTOKEN("https://api.weixin.qq.com/sns/oauth2/access_token", "GET", null),
    USER_FEED_MYTOTAL(DHMessage.PATH__USER_FEED_MYTOTAL_, DHMessage.METHOD__USER_FEED_MYTOTAL_, null),
    GROUP_TAKL_SETTAKLTOGROUP(DHMessage.PATH__GROUP_TAKL_SETTAKLTOGROUP_, DHMessage.METHOD__GROUP_TAKL_SETTAKLTOGROUP_, null),
    GROUP_TAKL_JOINUSERMAX(DHMessage.PATH__GROUP_TAKL_JOINUSERMAX_, DHMessage.METHOD__GROUP_TAKL_JOINUSERMAX_, null),
    GROUP_TAKL_KICK(DHMessage.PATH__GROUP_TAKL_KICK_, DHMessage.METHOD__GROUP_TAKL_KICK_, null),
    GROUP_TAKL_EXIT(DHMessage.PATH__GROUP_TAKL_EXIT_, DHMessage.METHOD__GROUP_TAKL_EXIT_, null),
    GROUP_TAKL_INVITE(DHMessage.PATH__GROUP_TAKL_INVITE_, DHMessage.METHOD__GROUP_TAKL_INVITE_, null),
    GROUP_TAKL_CREATE(DHMessage.PATH__GROUP_TAKL_CREATE_, DHMessage.METHOD__GROUP_TAKL_CREATE_, null),
    USER_FEED_UPLOADVIDEO(DHMessage.PATH__USER_FEED_UPLOADVIDEO_, DHMessage.METHOD__USER_FEED_UPLOADVIDEO_, null),
    CHAT_UPLOADVIDEO(DHMessage.PATH__CHAT_UPLOADVIDEO_, DHMessage.METHOD__CHAT_UPLOADVIDEO_, null),
    ACCOUNT_CHECKMOBILECODE(DHMessage.PATH__ACCOUNT_CHECKMOBILECODE_, DHMessage.METHOD__ACCOUNT_CHECKMOBILECODE_, null),
    ACTIVITY_COMMENT_GET(DHMessage.PATH__ACTIVITY_COMMENT_GET_, DHMessage.METHOD__ACTIVITY_COMMENT_GET_, null),
    ACTIVITY_COMMENT_CLUB(DHMessage.PATH__ACTIVITY_COMMENT_CLUB_, DHMessage.METHOD__ACTIVITY_COMMENT_CLUB_, null),
    ACTIVITY_COMMENT(DHMessage.PATH__ACTIVITY_COMMENT_, DHMessage.METHOD__ACTIVITY_COMMENT_, null),
    GROUP_MEMO_SET(DHMessage.PATH__GROUP_MEMO_SET_, DHMessage.METHOD__GROUP_MEMO_SET_, null),
    GROUP_MEMO_LIST_(DHMessage.PATH__GROUP_MEMO_LIST_, DHMessage.METHOD__GROUP_MEMO_LIST_, null),
    //	GROUP_MEMBER_SET(DHMessage.PATH__GROUP_MEMBER_SET,DHMessage.METHOD__GROUP_MEMBER_SET, null),
//	GROUP_MEMBER_MEMOS(DHMessage.PATH__GROUP_MEMBER_MEMOS,DHMessage.METHOD__GROUP_MEMBER_MEMOS, null),
    FRIEND_MEMO_SET(DHMessage.PATH__FRIEND_MEMO_SET_, DHMessage.METHOD__FRIEND_MEMO_SET_, null),
    FRIEND_MEMO_LIST(DHMessage.PATH__FRIEND_MEMO_LIST, DHMessage.METHOD__FRIEND_MEMO_LIST, null),
    BOOM_STATCOUNT(DHMessage.PATH__BOOM_STATCOUNT_, DHMessage.METHOD__BOOM_STATCOUNT_, null),
    BOOM_GETMYBOOMUSERLIST(DHMessage.PATH__BOOM_GETMYBOOMUSERLIST_, DHMessage.METHOD__BOOM_GETMYBOOMUSERLIST_, null),
    BOOM_GETMYBOOMLIST(DHMessage.PATH__BOOM_GETMYBOOMLIST_, DHMessage.METHOD__BOOM_GETMYBOOMLIST_, null),
    BOOM_ADDBOOM(DHMessage.PATH__BOOM_ADDBOOM_, DHMessage.METHOD__BOOM_ADDBOOM_, null),
    BOOM_OPENBOOM(DHMessage.PATH__BOOM_OPENBOOM_, DHMessage.METHOD__BOOM_OPENBOOM_, null),
    BOOM_NEWGIFT(DHMessage.PATH__BOOM_NEWGIFT_, DHMessage.METHOD__BOOM_NEWGIFT_, null),
    BOOM_NEWFOCUS(DHMessage.PATH__BOOM_NEWFOCUS_, DHMessage.METHOD__BOOM_NEWFOCUS_, null),
    BOOM_GETBOOMLIST(DHMessage.PATH__BOOM_GETBOOMLIST_, DHMessage.METHOD__BOOM_GETBOOMLIST_, null),
    BOOM_GETBOOMINFO(DHMessage.PATH__BOOM_GETBOOMINFO_, DHMessage.METHOD__BOOM_GETBOOMINFO_, null),
    BOOM_GETAREATOTAL(DHMessage.PATH__BOOM_GETAREATOTAL_, DHMessage.METHOD__BOOM_GETAREATOTAL_, null),
    USER_FEED_POST(DHMessage.PATH__USER_FEED_POST_, DHMessage.METHOD__USER_FEED_POST_, null),
    USER_FEED_DEL(DHMessage.PATH__USER_FEED_DEL_, DHMessage.METHOD__USER_FEED_DEL_, null),
    USER_FEED_LIST(DHMessage.PATH__USER_FEED_LIST_, DHMessage.METHOD__USER_FEED_LIST_, null),
    ME_FEED_MY(DHMessage.PATH__USER_FEED_MY_, DHMessage.METHOD__USER_FEED_MY_, null),
    DATE_CREATEORDER(DHMessage.PATH__DATE_CREATEORDER_, DHMessage.METHOD__DATE_CREATEORDER_, null),
    CHECK_VERSION(DHMessage.PATH__SYSTEM_CHECK_VERSION, DHMessage.METHOD__SYSTEM_CHECK_VERSION, null),
    ACCOUNT_PAY_MONEY_BUY(DHMessage.PATH__ACCOUNT_PAY_MONEY_BUY, DHMessage.METHOD__ACCOUNT_PAY_MONEY_BUY, null),
    DATE_RESPONSEADDDATETIME(DHMessage.PATH__DATE_RESPONSEADDDATETIME_, DHMessage.METHOD__DATE_RESPONSEADDDATETIME_, null),
    DATE_ADDPAYDATEORDER(DHMessage.PATH__DATE_ADDPAYDATEORDER_, DHMessage.METHOD__DATE_ADDPAYDATEORDER_, null),
    DATE_PAYDATEORDER(DHMessage.PATH__DATE_PAYDATEORDER_, DHMessage.METHOD__DATE_PAYDATEORDER_, null),
    GATEWAY(IDefine.gatewayURL, "GET", null),
    CONTACT_UPLOAD(DHMessage.PATH__CONTACT_UPLOAD_, DHMessage.METHOD__CONTACT_UPLOAD_, null),
    FRIEND_BRIEF(DHMessage.PATH__FRIEND_BRIEF_, DHMessage.METHOD__FRIEND_BRIEF_, null),
    CONTACT_USERLIST(DHMessage.PATH__CONTACT_USERLIST_, DHMessage.METHOD__CONTACT_USERLIST_, null),
    LOG_UPLOAD(DHMessage.PATH__LOG_UPLOAD, DHMessage.PATH__LOG_UPLOAD_METHOD, null),
    ACCOUNT_PAY_FINISH_ORDER(DHMessage.PATH__ACCOUNT_PAY_FINISH_ORDER, DHMessage.METHOD__ACCOUNT_PAY_FINISH_ORDER, null),
    ACCOUNT_PAY_CREATE_ORDER(DHMessage.PATH__ACCOUNT_PAY_CREATE_ORDER, DHMessage.METHOD__ACCOUNT_PAY_CREATE_ORDER, null),
    ACCOUNT_PAY_ANDROID_PRODUCTS(DHMessage.PATH__ACCOUNT_PAY_ANDROID_PRODUCTS, DHMessage.METHOD__ACCOUNT_PAY_ANDROID_PRODUCTS, null),
    ACCOUNT_PAY_VIP_GOODSLIST(DHMessage.PATH__ACCOUNT_PAY_VIP_GOODSLIST, DHMessage.METHOD__ACCOUNT_PAY_VIP_GOODSLIST, null),
    CLOUB_REMOVE_ROLETYPE(DHMessage.PATH__CLOUB_REMOVE_ROLETYPE_, DHMessage.METHOD__CLOUB_REMOVE_ROLETYPE_, null),
    FRIEND_BLACK_ADD(DHMessage.PATH__FRIEND_BLACK_ADD_, DHMessage.METHOD__FRIEND_BLACK_ADD_, null),
    USER_REPORT(DHMessage.PATH__USER_REPORT_, DHMessage.METHOD__USER_REPORT_, null),
    CLOUB_FEED(DHMessage.PATH__CLOUB_FEED_, DHMessage.METHOD__CLOUB_FEED_, null),
    ACCOUNT_LOGOUT(DHMessage.PATH__ACCOUNT_LOGOUT_, DHMessage.METHOD__ACCOUNT_LOGOUT_, null),
    DISCOVERY_FILTERINFO(DHMessage.PATH__DISCOVERY_FILTERINFO_, DHMessage.METHOD__DISCOVERY_FILTERINFO_, null),
    DISCOVERY_FILTERSET(DHMessage.PATH__DISCOVERY_FILTERSET_, DHMessage.METHOD__DISCOVERY_FILTERSET_, null),
    GIFT_GETSENDGIFTORDER(DHMessage.PATH__GIFT_GETSENDGIFTORDER_, DHMessage.METHOD__GIFT_GETSENDGIFTORDER_, null),
    USER_GEOS(DHMessage.PATH__USER_GEOS_, DHMessage.METHOD__USER_GEOS_, null),
    ACCOUNT_PAY_MONEY_PRODUCTS(DHMessage.PATH__ACCOUNT_PAY_MONEY_PRODUCTS_, DHMessage.METHOD__ACCOUNT_PAY_MONEY_PRODUCTS_, null),
    WALLET_INFO(DHMessage.PATH__WALLET_INFO_, DHMessage.METHOD__WALLET_INFO_, null),
    ACCOUNT_PAY_CHANNEL_LIST(DHMessage.PATH__ACCOUNT_PAY_CHANNEL_LIST_, DHMessage.METHOD__ACCOUNT_PAY_CHANNEL_LIST_, null),
    WALLET_DRAW_MONEY(DHMessage.PATH__WALLET_DRAW_MONEY_, DHMessage.METHOD__WALLET_DRAW_MONEY_, null),
    GROUP_INVITE_RESPONSE(DHMessage.PATH__GROUP_INVITE_RESPONSE_, DHMessage.METHOD__GROUP_INVITE_RESPONSE_, null),
    GROUP_APPLY_RESPONSE(DHMessage.PATH__GROUP_APPLY_RESPONSE_, DHMessage.METHOD__GROUP_APPLY_RESPONSE_, null),
    CLOUB_JOINRESPONSE(DHMessage.PATH__CLOUB_JOINRESPONSE_, DHMessage.METHOD__CLOUB_JOINRESPONSE_, null),
    DATE_RESPONSE(DHMessage.PATH__DATE_RESPONSE_, DHMessage.METHOD__DATE_RESPONSE_, null),
    DATE_RESPONSE_DETACH(DHMessage.PATH__DATE_RESPONSE_DETACH_, DHMessage.METHOD__DATE_RESPONSE_DETACH_, null),
    DATE_UPDATELOCATION(DHMessage.PATH__DATE_UPDATELOCATION_, DHMessage.METHOD__DATE_UPDATELOCATION_, null),
    DATE_SIGN(DHMessage.PATH__DATE_SIGN_, DHMessage.METHOD__DATE_SIGN_, null),
    DATE_DETACH(DHMessage.PATH__DATE_DETACH_, DHMessage.METHOD__DATE_DETACH_, null),
    DATE_COMMENT_GET(DHMessage.PATH__DATE_COMMENT_GET_, DHMessage.METHOD__DATE_COMMENT_GET_, null),
    DATE_COMMENT_CLUB(DHMessage.PATH__DATE_COMMENT_CLUB_, DHMessage.METHOD__DATE_COMMENT_CLUB_, null),
    DATE_COMMENT(DHMessage.PATH__DATE_COMMENT_, DHMessage.METHOD__DATE_COMMENT_, null),
    DATE_FINISH(DHMessage.PATH__DATE_FINISH_, DHMessage.METHOD__DATE_FINISH_, null),
    DATE_CANCEL(DHMessage.PATH__DATE_CANCEL_, DHMessage.METHOD__DATE_CANCEL_, null),
    DATE_CREATE(DHMessage.PATH__DATE_CREATE_, DHMessage.METHOD__DATE_CREATE_, null),
    DATE_INFO(DHMessage.PATH__DATE_INFO_, DHMessage.METHOD__DATE_INFO_, null),
    DATE_LIST(DHMessage.PATH__DATE_LIST_, DHMessage.METHOD__DATE_LIST_, null),
    ACTIVITY_MEMBERSET(DHMessage.PATH__ACTIVITY_MEMBERSET_, DHMessage.METHOD__ACTIVITY_MEMBERSET_, null),
    COMMENT_DEL(DHMessage.PATH__COMMENT_DEL_, DHMessage.METHOD__COMMENT_DEL_, null),
    ACTIVITY_SIGN(DHMessage.PATH__ACTIVITY_SIGN_, DHMessage.METHOD__ACTIVITY_SIGN_, null),
    ACTIVITY_CANCEL(DHMessage.PATH__ACTIVITY_CANCEL_, DHMessage.METHOD__ACTIVITY_CANCEL_, null),
    ACTIVITY_MEMBERS(DHMessage.PATH__ACTIVITY_MEMBERS_, DHMessage.METHOD__ACTIVITY_MEMBERS_, null),
    ACTIVITY_KICK(DHMessage.PATH__ACTIVITY_KICK_, DHMessage.METHOD__ACTIVITY_KICK_, null),
    ACTIVITY_FINISH(DHMessage.PATH__ACTIVITY_FINISH_, DHMessage.METHOD__ACTIVITY_FINISH_, null),
    ACTIVITY_FEEDEDL(DHMessage.PATH__ACTIVITY_FEEDDEL_, DHMessage.METHOD__ACTIVITY_FEEDDEL_, null),
    ACTIVITY_FEEDLIST(DHMessage.PATH__ACTIVITY_FEEDLIST_, DHMessage.METHOD__ACTIVITY_FEEDLIST_, null),
    ACTIVITY_FEED(DHMessage.PATH__ACTIVITY_FEED_, DHMessage.METHOD__ACTIVITY_FEED_, null),
    ACTIVITY_LOGO_SORT(DHMessage.PATH__ACTIVITY_LOGO_SORT_, DHMessage.METHOD__ACTIVITY_LOGO_SORT_, null),
    ACTIVITY_LOGO_LIST(DHMessage.PATH__ACTIVITY_LOGO_LIST_, DHMessage.METHOD__ACTIVITY_LOGO_LIST_, null),
    ACTIVITY_LOGO_DEL(DHMessage.PATH__ACTIVITY_LOGO_DEL_, DHMessage.METHOD__ACTIVITY_LOGO_DEL_, null),
    ACTIVITY_LOGO_ADD(DHMessage.PATH__ACTIVITY_LOGO_ADD_, DHMessage.METHOD__ACTIVITY_LOGO_ADD_, null),
    ACTIVITY_EXIT(DHMessage.PATH__ACTIVITY_EXIT_, DHMessage.METHOD__ACTIVITY_EXIT_, null),
    ACTIVITY_JOIN(DHMessage.PATH__ACTIVITY_JOIN_, DHMessage.METHOD__ACTIVITY_JOIN_, null),
    ACTIVITY_SET(DHMessage.PATH__ACTIVITY_SET_, DHMessage.METHOD__ACTIVITY_SET_, null),
    ACTIVITY_INFO(DHMessage.PATH__ACTIVITY_INFO_, DHMessage.METHOD__ACTIVITY_INFO_, null),
    ACTIVITY_CREATE(DHMessage.PATH__ACTIVITY_CREATE_, DHMessage.METHOD__ACTIVITY_CREATE_, null),
    SYSMSG_UNREAD_CLEAR(DHMessage.PATH__MSG_SYSMSG_UNREAD_CLEAR_, DHMessage.METHOD__MSG_SYSMSG_UNREAD_CLEAR_, null),
    MSG_SYSMSG_UNREAD_NUM(DHMessage.PATH__MSG_SYSMSG_UNREAD_NUM_, DHMessage.METHOD__MSG_SYSMSG_UNREAD_NUM_, null),
    MSG_UNREAD_CLEAR(DHMessage.PATH__MSG_UNREAD_CLEAR_, DHMessage.METHOD__MSG_UNREAD_CLEAR_, null),
    MSG_UNREAD(DHMessage.PATH__MSG_UNREAD_, DHMessage.METHOD__MSG_UNREAD_, null),
    CHAT_P2PCHATSTATUS(DHMessage.PATH__CHAT_P2PCHATSTATUS_, DHMessage.METHOD__CHAT_P2PCHATSTATUS_, null),
    CHAT_UNREADLIST(DHMessage.PATH__CHAT_UNREADLIST_, DHMessage.METHOD__CHAT_UNREADLIST_, null),
    CHAT_CHATLIST(DHMessage.PATH__CHAT_CHATLIST_, DHMessage.METHOD__CHAT_CHATLIST_, null),
    CHAT_UPLOADAUDIO(DHMessage.PATH__CHAT_UPLOADAUDIO_, DHMessage.METHOD__CHAT_UPLOADAUDIO_, null),
    CHAT_UPLOADIMG(DHMessage.PATH__CHAT_UPLOADIMG_, DHMessage.METHOD__CHAT_UPLOADIMG_, null),
    USER_SEARCH(DHMessage.PATH__USER_SEARCH_, DHMessage.METHOD__USER_SEARCH_, null),
    GROUP_INFO(DHMessage.PATH__GROUP_INFO_, DHMessage.METHOD__GROUP_INFO_, null),
    GROUP_SEARCH(DHMessage.PATH__GROUP_SEARCH_, DHMessage.METHOD__GROUP_SEARCH_, null),
    GROUP_SET(DHMessage.PATH__GROUP_SET_, DHMessage.METHOD__GROUP_SET_, null),
    GROUP_LOGO_DEL(DHMessage.PATH__GROUP_LOGO_DEL_, DHMessage.METHOD__GROUP_LOGO_DEL_, null),
    GROUP_LOGO_SORL(DHMessage.PATH__GROUP_LOGO_SORT_, DHMessage.METHOD__GROUP_LOGO_SORT_, null),
    GROUP_LOGO_LIST(DHMessage.PATH__GROUP_LOGO_LIST_, DHMessage.METHOD__GROUP_LOGO_LIST_, null),
    GROUP_LOGO_ADD(DHMessage.PATH__GROUP_LOGO_ADD_, DHMessage.METHOD__GROUP_LOGO_ADD_, null),
    GROUP_CREATE(DHMessage.PATH__GROUP_CREATE_, DHMessage.METHOD__GROUP_CREATE_, null),
    LOCATION_SEARCH(IDefine.searchPlaceURL, "GET", null),
    LOCATION_SEARCH_TEXT(IDefine.searchPlaceURLText, "GET", null),
    LOCATION_SEARCH_AROUND(IDefine.searchPlaceURLAround, "GET", null),
    GROUP_LEFTNUM(DHMessage.PATH__GROUP_LEFTNUM_, DHMessage.METHOD__GROUP_LEFTNUM_, null),
    CLUB_MYLIST(DHMessage.PATH__CLUB_MYLIST_, DHMessage.METHOD__CLUB_MYLIST_, null),
    DISCOVERY_REPORTGEO(DHMessage.PATH__DISCOVERY_REPORTGEO_, DHMessage.METHOD__DISCOVERY_REPORTGEO_, null),
    USER_WANTDATE(DHMessage.PATH__USER_WANTDATE_, DHMessage.METHOD__USER_WANTDATE_, null),
    ACCOUNT_MOBCODE(DHMessage.PATH__ACCOUNT_MOBCODE_, DHMessage.METHOD__ACCOUNT_MOBCODE_, null),
    USER_ROLE_MOBCODE(DHMessage.PATH_USER_ROLE_MOBCODE, DHMessage.METHOD_USER_ROLE_MOBCODE, null),
    ACCOUNT_MOBCODEEX(DHMessage.PATH__ACCOUNT_MOBCODEEX_, DHMessage.METHOD__ACCOUNT_MOBCODEEX_, null),
    ACCOUNT_REGISTER(DHMessage.PATH__ACCOUNT_REGISTER_, DHMessage.METHOD__ACCOUNT_REGISTER_, null),
    ACCOUNT_LOGIN(DHMessage.PATH__ACCOUNT_LOGIN_, DHMessage.METHOD__ACCOUNT_LOGIN_, null),
    ACCOUNT_MYINFO(DHMessage.PATH__ACCOUNT_MYINFO_, DHMessage.METHOD__ACCOUNT_MYINFO_, null),
    PHOTO_LOGO_ADD(DHMessage.PATH__PHOTO_LOGO_ADD_, DHMessage.METHOD__PHOTO_LOGO_ADD_, null),
    ACCOUNT_UPDATEINFO(DHMessage.PATH__ACCOUNT_UPDATEINFO_, DHMessage.METHOD__ACCOUNT_UPDATEINFO_, null),
    ACCOUNT_PSWDRESET(DHMessage.PATH__ACCOUNT_PSWDRESET_, DHMessage.METHOD__ACCOUNT_PSWDRESET_, null),
    FRIEND_FRIEND_LIST(DHMessage.PATH__FRIEND_FRIEND_LIST_, DHMessage.METHOD__FRIEND_FRIEND_LIST_, null),
    CLUB_NEARBY(DHMessage.PATH__CLUB_NEARBY_, DHMessage.METHOD__CLUB_NEARBY_, null),
    DISCOVERY_NEARBYLIST(DHMessage.PATH__DISCOVERY_NEARBYLIST_, DHMessage.METHOD__DISCOVERY_NEARBYLIST_, null),
    GROUP_APPLY(DHMessage.PATH__GROUP_APPLY_, DHMessage.METHOD__GROUP_APPLY_, null),
    GROUP_EXIT(DHMessage.PATH__GROUP_EXIT_, DHMessage.METHOD__GROUP_EXIT_, null),
    PHOTO_LOGO_LIST(DHMessage.PATH__PHOTO_LOGO_LIST_, DHMessage.METHOD__PHOTO_LOGO_LIST_, null),
    GROUP_MYLIST(DHMessage.PATH__GROUP_MYLIST_, DHMessage.METHOD__GROUP_MYLIST_, null),
    USER_MOREINFO(DHMessage.PATH__USER_MOREINFO_, DHMessage.METHOD__USER_MOREINFO_, null),
    USER_INFOS(DHMessage.PATH__USER_INFOS_, DHMessage.METHOD__USER_INFOS_, null),
    FRIEND_FOCUS_ADD(DHMessage.PATH__FRIEND_FOCUS_ADD_, DHMessage.METHOD__FRIEND_FOCUS_ADD_, null),
    FRIEND_FOCUS_CANCEL(DHMessage.PATH__FRIEND_FOCUS_CANCEL_, DHMessage.METHOD__FRIEND_FOCUS_CANCEL_, null),
    FRIEND_RELATIONS(DHMessage.PATH__FRIEND_RELATIONS_, DHMessage.METHOD__FRIEND_RELATIONS_, null),
    COMMENT_LIST(DHMessage.PATH__COMMENT_LIST_, DHMessage.METHOD__COMMENT_LIST_, null),
    USER_SET(DHMessage.PATH__USER_SET_, DHMessage.METHOD__USER_SET_, null),
    PHOTO_UPLOAD(DHMessage.PATH__PHOTO_UPLOAD_, DHMessage.METHOD__PHOTO_UPLOAD_, null),
    PHOTO_LOGO_SORT(DHMessage.PATH__PHOTO_LOGO_SORT_, DHMessage.METHOD__PHOTO_LOGO_SORT_, null),
    FRIEND_FAN_LIST(DHMessage.PATH__FRIEND_FAN_LIST_, DHMessage.METHOD__FRIEND_FAN_LIST_, null),
    FRIEND_FOCUS_LIST(DHMessage.PATH__FRIEND_FOCUS_LIST_, DHMessage.METHOD__FRIEND_FOCUS_LIST_, null),
    USER_ROLE_VERIFY(DHMessage.PATH__USER_ROLE_VERIFY_, DHMessage.METHOD__USER_ROLE_VERIFY_, null),
    SYSMSG_LIST(DHMessage.PATH__MSG_SYSMSG_LIST_, DHMessage.METHOD__MSG_SYSMSG_LIST_, null),
    CLUB_FOCUS(DHMessage.PATH__CLUB_FOCUS_, DHMessage.METHOD__CLUB_FOCUS_, null),
    CLUB_UNFOCUS(DHMessage.PATH__CLUB_UNFOCUS_, DHMessage.METHOD__CLUB_UNFOCUS_, null),
    FRIEND_VISITOR_LIST(DHMessage.PATH__FRIEND_VISITOR_LIST_, DHMessage.METHOD__FRIEND_VISITOR_LIST_, null),
    FRIEND_VISITOR_COUNT(DHMessage.PATH__FRIEND_VISITOR_COUNT_, DHMessage.METHOD__FRIEND_VISITOR_COUNT_, null),
    GIFT_MYLIST(DHMessage.PATH__GIFT_MYLIST_, DHMessage.METHOD__GIFT_MYLIST_, null),
    ACTIVITY_MYLIST(DHMessage.PATH__ACTIVITY_MYLIST_, DHMessage.METHOD__ACTIVITY_MYLIST_, null),
    USER_COMMENT_LIST(DHMessage.PATH__USER_COMMENT_LIST_, DHMessage.METHOD__USER_COMMENT_LIST_, null),
    FRIEND_BLACK_LIST(DHMessage.PATH__FRIEND_BLACK_LIST_, DHMessage.METHOD__FRIEND_BLACK_LIST_, null),
    CLOUB_INFO(DHMessage.PATH__CLOUB_INFO_, DHMessage.METHOD__CLOUB_INFO_, null),
    ACCOUNT_PSWDMOD(DHMessage.PATH__ACCOUNT_PSWDMOD_, DHMessage.METHOD__ACCOUNT_PSWDMOD_, null),
    GIFT_SUMARY(DHMessage.PATH__GIFT_SUMARY_, DHMessage.METHOD__GIFT_SUMARY_, null),
    GIFT_LIST(DHMessage.PATH__GIFT_LIST_, DHMessage.METHOD__GIFT_LIST_, null),
    CLUB_INFO(DHMessage.PATH__CLUB_INFO_, DHMessage.METHOD__CLUB_INFO_, null),
    HOME_SENDGIFT(DHMessage.PATH__HOME_SENDGIFT_, DHMessage.METHOD__HOME_SENDGIFT_, null),
    COMMENT_POST(DHMessage.PATH__COMMENT_POST_, DHMessage.METHOD__COMMENT_POST_, null),
    PHOTO_LOGO_DEL(DHMessage.PATH__PHOTO_LOGO_DEL_, DHMessage.METHOD__PHOTO_LOGO_DEL_, null),
    GROUP_MEMBERS(DHMessage.PATH__GROUP_MEMBERS_, DHMessage.METHOD__GROUP_MEMBERS_, null),
    ACTIVITY_GROUPLIST(DHMessage.PATH__ACTIVITY_GROUPLIST_, DHMessage.METHOD__ACTIVITY_GROUPLIST_, null),
    GROUP_CHECKAPPLY(DHMessage.PATH__GROUP_CHECKAPPLY_, DHMessage.METHOD__GROUP_CHECKAPPLY_, null),
    GROUP_MYSET(DHMessage.PATH__GROUP_MYSET_, DHMessage.METHOD__GROUP_MYSET_, null),
    GROUP_INVITE(DHMessage.PATH__GROUP_INVITE_, DHMessage.METHOD__GROUP_INVITE_, null),
    GROUP_KICK(DHMessage.PATH__GROUP_KICK_, DHMessage.METHOD__GROUP_KICK_, null),
    CLUB_PHOTO_LIST(DHMessage.PATH__CLUB_PHOTO_LIST_, DHMessage.METHOD__CLUB_PHOTO_LIST_, null),
    GROUP_LIST_CLUBID(DHMessage.PATH__GROUP_LIST_CLUBID_, DHMessage.METHOD__GROUP_LIST_CLUBID_, null),
    CLOUB_FEEDLIST(DHMessage.PATH__CLOUB_FEEDLIST_, DHMessage.METHOD__CLOUB_FEEDLIST_, null),
    CLOUB_FEEDDEL(DHMessage.PATH__CLOUB_FEEDDEL_, DHMessage.METHOD__CLOUB_FEEDDEL_, null),
    FRIEND_BLACK_CANCEL(DHMessage.PATH__FRIEND_BLACK_CANCEL_, DHMessage.METHOD__FRIEND_BLACK_CANCEL_, null),
    USER_ROLE_UNVERIFY(DHMessage.PATH__USER_ROLE_UNVERIFY_, DHMessage.METHOD__USER_ROLE_UNVERIFY_, null),
    CLUB_PHOTO_ADD(DHMessage.PATH__CLUB_PHOTO_ADD_, DHMessage.METHOD__CLUB_PHOTO_ADD_, null),
    CLUB_PHOTO_DEL(DHMessage.PATH__CLUB_PHOTO_DEL_, DHMessage.METHOD__CLUB_PHOTO_DEL_, null),
    CLUB_LOGO_ADD(DHMessage.PATH__CLUB_LOGO_ADD_, DHMessage.METHOD__CLUB_LOGO_ADD_, null),
    CLOUB_INVITEJOIN(DHMessage.PATH__CLOUB_INVITEJOIN_, DHMessage.METHOD__CLOUB_INVITEJOIN_, null),
    CLOUB_SET(DHMessage.PATH__CLOUB_SET_, DHMessage.METHOD__CLOUB_SET_, null),
    MASTER_APPLY(DHMessage.PATH__MASTER_APPLY_, DHMessage.METHOD__MASTER_APPLY_, null),
    MASTER_LIST(DHMessage.PATH__MASTER_LIST_, DHMessage.METHOD__MASTER_LIST_, null),
    MASTER_APPRENTICES_LIST(DHMessage.PATH__MASTER_APPRENTICES_LIST_, DHMessage.METHOD__MASTER_APPRENTICES_LIST_, null),
    MASTER_APPLY_INFO(DHMessage.PATH__MASTER_APPLY_INFO_, DHMessage.METHOD__MASTER_APPLY_INFO_, null),
    MASTER_SORT(DHMessage.PATH__MASTER_SORT_, DHMessage.METHOD__MASTER_SORT_, null),
    MASTER_DISCONNECT(DHMessage.PATH__MASTER_DISCONNECT_, DHMessage.METHOD__MASTER_DISCONNECT_, null),
    MASTER_APPEND(DHMessage.PATH__MASTER_APPEND_, DHMessage.METHOD__MASTER_APPEND_, null),
    MASTER_APPLY_RESPONSE(DHMessage.PATH__MASTER_APPLY_RESPONSE_, DHMessage.METHOD__MASTER_APPLY_RESPONSE_, null),
    WALLET_APPLY_REWARD(DHMessage.PATH__WALLET_APPLY_REWARD_, DHMessage.METHOD__WALLET_APPLY_REWARD_, null),
    USER_FEED_MY(DHMessage.PATH__USER_FEED_MY_, DHMessage.METHOD__USER_FEED_MY_, null),
    USER_INTROAUDIO(DHMessage.PATH__USER_INTROAUDIO_, DHMessage.METHOD__USER_INTROAUDIO_, null),
    USER_INTROAUDIO_DEL(DHMessage.PATH__USER_INTROAUDIO_DEL_, DHMessage.METHOD__USER_INTROAUDIO_DEL_, null),
    MASTER_GIFTS(DHMessage.PATH__MASTER_GIFTS_, DHMessage.METHOD__MASTER_GIFTS_, null),
    AD_GETAD(DHMessage.PATH__AD_GETAD_, DHMessage.METHOD__AD_GETAD_, null),
    USER_ROLE_MODIFY_REALNAME(DHMessage.PATH__USER_ROLE_MODIFY_REALNAME_, "POST", null),
    FRIEND_VISITOR_ADD(DHMessage.PATH__FRIEND_VISITOR_ADD_, DHMessage.METHOD__FRIEND_VISITOR_ADD_, null),
    REDPACKAGE_CREATE(DHMessage.PATH__REDPACKAGE_CREATE_, DHMessage.METHOD__REDPACKAGE_CREATE_, null),
    REDPACKAGE_INFO(DHMessage.PATH__REDPACKAGE_INFO_, DHMessage.METHOD__REDPACKAGE_INFO_, null),
    REDPACKAGE_OPEN(DHMessage.PATH__REDPACKAGE_OPEN_, DHMessage.METHOD__REDPACKAGE_OPEN_, null),
    REDPACKAGE_RESEND(DHMessage.PATH__REDPACKAGE_RESEND_, DHMessage.METHOD__REDPACKAGE_RESEND_, null),
    DISCOVERY_PIAZZLIST(DHMessage.PATH__DISCOVERY_PIAZZLIST_, DHMessage.METHOD__DISCOVERY_PIAZZLIST_, null),
    SETTINGS_GETPIAZZASETTINGS(DHMessage.PATH__SETTINGS_GETPIAZZASETTINGS_, DHMessage.METHOD__SETTINGS_GETPIAZZASETTINGS_, null),
    ARTICLE_LIST(DHMessage.PATH__ARTICLE_LIST_, DHMessage.METHOD__ARTICLE_LIST_, null),
    ARTICLE_SHARE(DHMessage.PATH__ARTICLE_SHARE_, DHMessage.METHOD__ARTICLE_SHARE_, null),
    ARTICLE_COMMENT(DHMessage.PATH__ARTICLE_COMMENT_, DHMessage.METHOD__ARTICLE_COMMENT_, null),
    COMMENT_ARTICLELIST(DHMessage.PATH__COMMENT_ARTICLELIST_, DHMessage.METHOD__COMMENT_ARTICLELIST_, null),
    GROUP_CARD_CREATE(DHMessage.PATH__GROUP_CARD_CREATE_, DHMessage.METHOD__GROUP_CARD_CREATE_, null),
    GROUP_CARD_LIST(DHMessage.PATH__GROUP_CARD_LIST_, DHMessage.METHOD__GROUP_CARD_LIST_, null),
    GROUP_CARD_DEL(DHMessage.PATH__GROUP_CARD_DEL_, DHMessage.METHOD__GROUP_CARD_DEL_, null),
    GROUP_CARD_EDIT(DHMessage.PATH__GROUP_CARD_EDIT_, DHMessage.METHOD__GROUP_CARD_EDIT_, null),
    DISCOVERY_NEARBYFEEDLIST(DHMessage.PATH__DISCOVERY_NEARBYFEEDLIST_, DHMessage.METHOD__DISCOVERY_NEARBYFEEDLIST_, null),
    TEACHING_USERTRAIN_STAT(DHMessage.PATH__TEACHING_USERTRAIN_STAT_, DHMessage.METHOD__TEACHING_USERTRAIN_STAT_, null),
    TEACHING_USERTRAIN_LIST(DHMessage.PATH__TEACHING_USERTRAIN_LIST_, DHMessage.METHOD__TEACHING_USERTRAIN_LIST_, null),
    TEACHING_SPECIAL_LIST(DHMessage.PATH__TEACHING_SPECIAL_LIST_, DHMessage.METHOD__TEACHING_SPECIAL_LIST_, null),
    TEACHING_CATEGORY_LIST(DHMessage.PATH__TEACHING_CATEGORY_LIST_, DHMessage.METHOD__TEACHING_CATEGORY_LIST_, null),
    TEACHING_TEACHER_LIST(DHMessage.PATH__TEACHING_TEACHER_LIST_, DHMessage.METHOD__TEACHING_TEACHER_LIST_, null),
    TEACHING_TRAIN_LIST(DHMessage.PATH__TEACHING_TRAIN_LIST_, DHMessage.METHOD__TEACHING_TRAIN_LIST_, null),
    TEACHING_USERTRAIN_ADD(DHMessage.PATH__TEACHING_USERTRAIN_ADD_, DHMessage.METHOD__TEACHING_USERTRAIN_ADD_, null),
    TEACHING_SPECIAL_INFO(DHMessage.PATH__TEACHING_SPECIAL_INFO_, DHMessage.METHOD__TEACHING_SPECIAL_INFO_, null),
    TEACHING_USERTRAIN_DEL(DHMessage.PATH__TEACHING_USERTRAIN_DEL_, DHMessage.METHOD__TEACHING_USERTRAIN_DEL_, null),
    TEACHING_TRAIN_INFO(DHMessage.PATH__TEACHING_TRAIN_INFO_, DHMessage.METHOD__TEACHING_TRAIN_INFO_, null),
    TEACHING_USERTRAINFINISH_LIST(DHMessage.PATH__TEACHING_USERTRAINFINISH_LIST_, DHMessage.METHOD__TEACHING_USERTRAINFINISH_LIST_, null),
    TEACHING_USERTRAIN_FINISHGROUP(DHMessage.PATH__TEACHING_USERTRAIN_FINISHGROUP_, DHMessage.METHOD__TEACHING_USERTRAIN_FINISHGROUP_, null),
    TEACHING_FEEDDEL(DHMessage.PATH__TEACHING_FEEDDEL_, DHMessage.METHOD__TEACHING_FEEDDEL_, null),
    TEACHING_FEEDLIST(DHMessage.PATH__TEACHING_FEEDLIST_, DHMessage.METHOD__TEACHING_FEEDLIST_, null),
    TEACHING_FEED(DHMessage.PATH__TEACHING_FEED_, DHMessage.METHOD__TEACHING_FEED_, null),
    TEACHING_RATING_LIST(DHMessage.PATH__TEACHING_RATING_LIST_, DHMessage.METHOD__TEACHING_RATING_LIST_, null),
    TEACHING_RATING_INFO(DHMessage.PATH__TEACHING_RATING_INFO_, DHMessage.METHOD__TEACHING_RATING_INFO_, null),
    TEACHING_USERRATING_LIST(DHMessage.PATH__TEACHING_USERRATING_LIST_, DHMessage.METHOD__TEACHING_USERRATING_LIST_, null),
    TEACHING_USERRATING_FINISHONE(DHMessage.PATH__TEACHING_USERRATING_FINISHONE_, DHMessage.METHOD__TEACHING_USERRATING_FINISHONE_, null),
    TEACHING_USERRATING_START(DHMessage.PATH__TEACHING_USERRATING_START_, DHMessage.METHOD__TEACHING_USERRATING_START_, null),
    TEACHING_USERRATING_RESTART(DHMessage.PATH__TEACHING_USERRATING_RESTART_, DHMessage.METHOD__TEACHING_USERRATING_RESTART_, null),
    TEACHING_USERRATING_MYLIST(DHMessage.PATH__TEACHING_USERRATING_MYLIST_, DHMessage.METHOD__TEACHING_USERRATING_MYLIST_, null),
    TEACHING_USERRATING_INFO(DHMessage.PATH__TEACHING_USERRATING_INFO_, DHMessage.METHOD__TEACHING_USERRATING_INFO_, null),
    USER_ROLETYPE_COUNT(DHMessage.PATH__USER_ROLETYPE_COUNT_, DHMessage.METHOD__USER_ROLETYPE_COUNT_, null),
    GROUP_COUNT(DHMessage.PATH__GROUP_COUNT_, DHMessage.METHOD__GROUP_COUNT_, null),
    DISCOVERY_NEARUSERCOUNT(DHMessage.PATH__DISCOVERY_NEARUSERCOUNT_, DHMessage.METHOD__DISCOVERY_NEARUSERCOUNT_, null),
    TEACHING_SHARE_FINISH(DHMessage.PATH__TEACHING_SHARE_FINISH_, DHMessage.METHOD__TEACHING_SHARE_FINISH_, null),
    CLUB_SEARCH(DHMessage.PATH__CLUB_SEARCH_, DHMessage.METHOD__CLUB_SEARCH_, null),
    USER_COMMENT_TAGS(DHMessage.PATH__USER_COMMENT_TAGS_, DHMessage.METHOD__USER_COMMENT_TAGS_, null),
    USER_LIST_ADDRESS(DHMessage.PATH__USER_LIST_ADDRESS_, DHMessage.METHOD__USER_LIST_ADDRESS_, null),
    PRIZE_CONFIRM_ADDRESS(DHMessage.PATH__PRIZE_CONFIRM_ADDRESS_, DHMessage.METHOD__PRIZE_CONFIRM_ADDRESS_, null),
    GAME_CREATE_ROOM(DHMessage.PATH_GAME_CREATE_ROOM, DHMessage.METHOD_GAME_CREATE_ROOM, null),
    GAME_JOINQR(DHMessage.PATH_GAME_JOINQR, DHMessage.METHOD_GAME_JOINQR, null),
    GAME_JOINQR_MATCH(DHMessage.PATH_GAME_JOINQR_MATCH, DHMessage.METHOD_GAME_JOINQR_MATCH, null),
    LISTS_SEARCH(DHMessage.PATH_LISTS_SEARCH, DHMessage.METHOD_LISTS_SEARCH, null),
    LISTS_GAME_ORDER(DHMessage.PATH_LISTS_GAME_ORDER, DHMessage.METHOD_LISTS_GAME_ORDER, null),
    GAME_GETMYSTATDATA(DHMessage.PATH_GAME_GETMYSTATDATA, DHMessage.METHOD_GAME_GETMYSTATDATA, null),
    GAME_GETMYROOMLIST(DHMessage.PATH_GAME_GETMYROOMLIST, DHMessage.METHOD_GAME_GETMYROOMLIST, null),
    GAME_GETMYVIDEOROOMLIST(DHMessage.PATH_GAME_GETMYVIDEOROOMLIST, DHMessage.METHOD_GAME_GETMYVIDEOROOMLIST, null),
    GAME_GETMYALLSTATDATA(DHMessage.PATH_GAME_GETMYALLSTATDATA, DHMessage.METHOD_GAME_GETMYALLSTATDATA, null),
    GAME_GETMYSTATLIST(DHMessage.PATH_GAME_GETMYSTATLIST, DHMessage.METHOD_GAME_GETMYSTATLIST, null),
    GAMEONLINE_INVITE_LIST(DHMessage.PATH_GAMEONLINE_INVITE_LIST, DHMessage.METHOD_GAMEONLINE_INVITE_LIST, null),
    GAMEONLINE_INVITE_LIST_V3(DHMessage.PATH_GAMEONLINE_INVITE_LIST_V3, DHMessage.METHOD_GAMEONLINE_INVITE_LIST_V3, null),
    GAMEONLINE_CREATENETROOM(DHMessage.PATH_GAMEONLINE_CREATENETROOM, DHMessage.METHOD_GAMEONLINE_CREATENETROOM, null),
    GAMEONLINE_SEND_CONTENT(DHMessage.PATH_GAMEONLINE_SEND_CONTENT, DHMessage.METHOD_GAMEONLINE_SEND_CONTENT, null),
    GAMEONLINE_READY_START(DHMessage.PATH_GAMEONLINE_READY_START, DHMessage.METHOD_GAMEONLINE_READY_START, null),
    GAMEONLINE_CONTINUE_GAME(DHMessage.PATH_GAMEONLINE_CONTINUE_GAME, DHMessage.METHOD_GAMEONLINE_CONTINUE_GAME, null),
    GAMEONLINE_MY_IN_ROOM(DHMessage.PATH_GAMEONLINE_MY_IN_ROOM, DHMessage.METHOD_GAMEONLINE_MY_IN_ROOM, null),
    GAMEONLINE_INVITE_SEARCH(DHMessage.PATH_GAMEONLINE_INVITE_SEARCH, DHMessage.METHOD_GAMEONLINE_INVITE_SEARCH, null),
    GAME_SIG_LIVE(DHMessage.PATH_SIG_LIVE_GAME, DHMessage.METHOD_SIG_LIVE_GAME, null),
    EXIT_NET_ROOM_HTTP(DHMessage.PATH_EXIT_NET_ROOM_HTTP, DHMessage.METHOD_EXIT_NET_ROOM_HTTP, null),
    ACCOUNT_WX_LOGIN(DHMessage.PATH_ACCOUNT_WX_LOGIN, DHMessage.METHOD_ACCOUNT_WX_LOGIN, null),
    ACCOUNT_OPEN_REGISTER(DHMessage.PATH_ACCOUNT_OPEN_REGISTER, DHMessage.METHOD_ACCOUNT_OPEN_REGISTER, null),
    ACCOUNT_OPEN_REGISTER_MOBILE(DHMessage.PATH_ACCOUNT_OPEN_REGISTER_MOBILE, DHMessage.METHOD_ACCOUNT_OPEN_REGISTER_MOBILE, null),
    ACCOUNT_OPENMOBCODE(DHMessage.PATH_ACCOUNT_OPENMOBCODE, DHMessage.METHOD_ACCOUNT_OPENMOBCODE, null),
    LISTS_USER_START(DHMessage.PATH_LISTS_USERS_START, DHMessage.METHOD_LISTS_USERS_START, null),
    CONFIG_GAMELIST(DHMessage.PATH_CONFIG_GAMELIST, DHMessage.METHOD_CONFIG_GAMELIST, null),
    UPLOAD_DATA(DHMessage.PATH_UPLOAD_DATA_URL, DHMessage.METHOD_UPLOAD_POST, null),
    GAME_GETROOMDETAIL(DHMessage.PATH_GAME_GETROOMDETAIL, DHMessage.METHOD_GAME_GETROOMDETAIL, null),
    MATCHGAME_MATCH_DETAIL(DHMessage.PATH_MATCHGAME_MATCH_DETAIL, DHMessage.METHOD_MATCHGAME_MATCH_DETAIL, null),
    USER_ROLE_LIST_STATUS(DHMessage.PATH_USER_ROLE_LIST_STATUS_URL, DHMessage.METHOD_ROLE_LIST_STATUS_GET, null),
    SHOP_GETORDERINFOBYNUMBER(DHMessage.PATH_SHOP_GETORDERINFOBYNUMBER_URL, DHMessage.METHOD_SHOP_GETORDERINFOBYNUMBER_POST, null),
    MATCH_GETPAYMATCHMONEY(DHMessage.PATH_MATCH_GETPAYMATCHMONEY_URL, DHMessage.METHOD_MATCH_GETPAYMATCHMONEY_POST, null),
    GAMEHALL_GET_SETTINGS(DHMessage.PATH_GAMEHALL_GET_SETTINGS_URL, DHMessage.METHOD_GAMEHALL_GET_SETTINGS_GET, null),
    GAMEHALL_SETTINGS(DHMessage.PATH_GAMEHALL_SETTINGS_URL, DHMessage.METHOD_GAMEHALL_SETTINGS_POST, null),
    GAMEHALL_ONLINE_COUNT(DHMessage.PATH_GAMEHALL_ONLINE_COUNT_URL, DHMessage.METHOD_GAMEHALL_ONLINE_COUNT_GET, null),
    GAMEHALL_GO_HALL(DHMessage.PATH_GAMEHALL_GO_HALL_URL, DHMessage.METHOD_GAMEHALL_GO_HALL_GET, null),
    GAMEHALL_FAST_MATCH(DHMessage.PATH_GAMEHALL_FAST_MATCH_URL, DHMessage.METHOD_GAMEHALL_FAST_MATCH_GET, null),
    GAMEHALL_JOIN_ROOM(DHMessage.PATH_GAMEHALL_JOIN_ROOM_URL, DHMessage.METHOD_GAMEHALL_JOIN_ROOM_POST, null),
    GAMEHALL_EXIT_HALL(DHMessage.PATH_GAMEHALL_EXIT_HALL_URL, DHMessage.METHOD_GAMEHALL_EXIT_HALL_POST, null),
    GAMEHALL_SEND_HALL_CONTENT(DHMessage.PATH_GAMEHALL_SEND_HALL_CONTENT_URL, DHMessage.METHOD_GAMEHALL_SEND_HALL_CONTENT_POST, null),
    ACCOUNT_PAY_GOLD_BUYLIST(DHMessage.PATH_ACCOUNT_PAY_GOLD_BUYLIST_URL, DHMessage.METHOD_ACCOUNT_PAY_GOLD_BUYLIST_GET, null),
    ACCOUNT_PAY_GIFT_BAG_LIST(DHMessage.PATH_ACCOUNT_PAY_GIFT_BAG_LIST_URL, DHMessage.METHOD_ACCOUNT_PAY_GIFT_BAG_LIST_GET, null),
    TASK_CHECK(DHMessage.PATH_TASK_CHECK_URL, DHMessage.METHOD_TASK_CHECK_GET, null),
    TASK_FINISH(DHMessage.PATH_TASK_FINISH_URL, DHMessage.METHOD_TASK_FINISH_POST, null),
    SHOP_VIPCARDEXCHANGE(DHMessage.PATH_SHOP_VIPCARDEXCHANGE_URL, DHMessage.METHOD_SHOP_VIPCARDEXCHANGE_POST, null),
    USER_IS_BIND_WX(DHMessage.PATH_USER_IS_BIND_WX_URL, DHMessage.METHOD_USER_IS_BIND_WX_GET, null),
    USER_BIND_WX(DHMessage.PATH_USER_BIND_WX_URL, DHMessage.METHOD_USER_BIND_WX_POST, null),
    GAMEUSER_GOLD_LINE(DHMessage.PATH_GAMEUSER_GOLD_LINE_URL, DHMessage.METHOD_GAMEUSER_GOLD_LINE_GET, null),
    SHOP_ISCOUPONCODESTATUS(DHMessage.PATH_SHOP_ISCOUPONCODESTATUS_URL, DHMessage.METHOD_SHOP_ISCOUPONCODESTATUS_POST, null),
    GAMEHALL_GETGAMEGOLDDETAIL(DHMessage.PATH_GAMEHALL_GETGAMEGOLDDETAIL_URL, DHMessage.METHOD_GAMEHALL_GETGAMEGOLDDETAIL_GET, null),
    GAMEHALL_USER_LIST(DHMessage.PATH_GAMEHALL_USER_LIST_URL, DHMessage.METHOD_GAMEHALL_USER_LIST_GET, null),
    SHOP_SHOPPAYMENTAPP(DHMessage.PATH_SHOP_SHOPPAYMENTAPP_URL, DHMessage.METHOD_SHOP_SHOPPAYMENTAPP_POST, null),
    MATCH_MATCHPAYMENTAPP(DHMessage.PATH_MATCH_MATCHPAYMENTAPP_URL, DHMessage.METHOD_MATCH_MATCHPAYMENTAPP_POST, null),
    ACCOUNT_PAY_ORDERSTATUS(DHMessage.PATH_ACCOUNT_PAY_ORDERSTATUS_URL, DHMessage.METHOD_ACCOUNT_PAY_ORDERSTATUS_GET, null),
    MATCH_MATCHLIST(DHMessage.PATH_MATCH_MATCHLIST_URL, DHMessage.METHOD_MATCH_MATCHLIST_GET, null),
    USER_CURMONTH_SIGNLIST(DHMessage.PATH_USER_CURMONTH_SIGNLIST_URL, DHMessage.METHOD_USER_CURMONTH_SIGNLIST_GET, null),
    USER_EVERY_DAY_SIGN(DHMessage.PATH_USER_EVERY_DAY_SIGN_URL, DHMessage.METHOD_USER_EVERY_DAY_SIGN_GET, null),
    TASK_LIST(DHMessage.PATH_TASK_LIST_URL, DHMessage.METHOD_TASK_LIST_GET, null),
    GAMEUSER_MEDAL_LIST(DHMessage.PATH_GAMEUSER_MEDAL_LIST_URL, DHMessage.METHOD_GAMEUSER_MEDAL_LIST_GET, null),
    GAMEUSER_EXP_MEDAL(DHMessage.PATH_GAMEUSER_EXP_MEDAL_URL, DHMessage.METHOD_GAMEUSER_EXP_MEDAL_GET, null),
    USER_CAN_EVERY_DAY_SIGN(DHMessage.PATH_USER_CAN_EVERY_DAY_SIGN_URL, DHMessage.METHOD_USER_CAN_EVERY_DAY_SIGN_GET, null),
    ACCOUNT_MOBCODE_LOGIN(DHMessage.PATH_ACCOUNT_MOBCODE_LOGIN, DHMessage.METHOD_ACCOUNT_MOBCODE_LOGIN, null),
    ACCOUNT_MOBILE_LOGIN(DHMessage.PATH_ACCOUNT_MOBILE_LOGIN, DHMessage.METHOD_ACCOUNT_MOBILE_LOGIN, null),
    GAMEUSER_MEDAL_INFO(DHMessage.PATH_GAMEUSER_MEDAL_INFO_URL, DHMessage.METHOD_GAMEUSER_MEDAL_INFO_GET, null),
    ACCOUNT_GETBINDINFO(DHMessage.PATH_ACCOUNT_GETBINDINFO_URL, DHMessage.METHOD_ACCOUNT_GETBINDINFO_GET, null),
    GAME_SCANQR(DHMessage.PATH_GAME_SCANQR_URL, DHMessage.METHOD_GAME_SCANQR_POST, null),
    GAME_SCANQR_RESPONES(DHMessage.PATH_GAME_SCANQR_RESPONES_URL, DHMessage.METHOD_GAME_SCANQR_RESPONES_POST, null),
    GAMEHALL_IS_EVERYDAY_GOLD(DHMessage.PATH_GAMEHALL_IS_EVERYDAY_GOLD_URL, DHMessage.METHOD_GAMEHALL_IS_EVERYDAY_GOLD_GET, null),
    GAMEHALL_EVERYDAY_GOLD(DHMessage.PATH_GAMEHALL_EVERYDAY_GOLD_URL, DHMessage.METHOD_GAMEHALL_EVERYDAY_GOLD_GET, null),
    ONLINEMATCH_MASTER_LIST(DHMessage.PATH_ONLINEMATCH_MASTER_LIST_URL, DHMessage.METHOD_ONLINEMATCH_MASTER_LIST_GET, null),
    USER_ROLE_VERIFY_DATA(DHMessage.PATH_USER_ROLE_VERIFY_DATA_URL, DHMessage.METHOD_USER_ROLE_VERIFY_DATA_GET, null),
    ARTICLE_CLICK(DHMessage.PATH__ARTICLE_CLICK_, DHMessage.METHOD__ARTICLE_CLICK_, null),
    MATCH_DAY_LIST(DHMessage.PATH_DAY_MATCH_LIST_URL, DHMessage.METHOD_DAY_MATCH_LIST_GET, null),
    MATCH_DAY_LIST_STATUS(DHMessage.PATH_DAY_MATCH_LIST_STATUS_URL, DHMessage.METHOD_DAY_MATCH_LIST_STATUS_GET, null),
    MATCH_DAY_STAT_DATA(DHMessage.PATH_DAY_STAT_DATA_URL, DHMessage.METHOD_DAY_STAT_DATA_GET, null),
    MATCH_GO_IN_MATCH(DHMessage.PATH_GO_IN_MATCH_URL, DHMessage.METHOD_GO_IN_MATCH_GET, null),
    MATCH_GO_OUT_MATCH(DHMessage.PATH_GO_OUT_MATCH_URL, DHMessage.METHOD_GO_OUT_MATCH_POST, null),
    MATCH_CUR_ORDER_LIST(DHMessage.PATH_CUR_ORDER_LIST_URL, DHMessage.METHOD_CUR_ORDER_LIST_GET, null),
    MATCH_GAME_LIST(DHMessage.PATH_MATCH_GAME_LIST_URL, DHMessage.METHOD_MATCH_GAME_LIST_GET, null),
    MATCH_SEND_CONTENT(DHMessage.PATH_MATCH_SEND_CONTENT_URL, DHMessage.METHOD_MATCH_SEND_CONTENT_POST, null),
    MATCH_JOIN_MATCH(DHMessage.PATH_MATCH_JOIN_MATCH_URL, DHMessage.METHOD_MATCH_JOIN_MATCH_POST, null),
    MATCH_EXIT_MATCH(DHMessage.PATH_MATCH_EXIT_MATCH_URL, DHMessage.METHOD_MATCH_EXIT_MATCH_POST, null),
    MATCH_ORDER_LIST(DHMessage.PATH_MATCH_ORDER_LIST_URL, DHMessage.METHOD_MATCH_ORDER_LIST_POST, null),
    MATCH_VIDEO_INFO(DHMessage.PATH_MATCH_VIDEO_INFO_URL, DHMessage.METHOD_MATCH_VIDEO_INFO_GET, null),
    ONLINEMATCH_CHECK_GET_VIP(DHMessage.PATH_ONLINEMATCH_CHECK_GET_VIP_URL, DHMessage.METHOD_ONLINEMATCH_CHECK_GET_VIP_GET, null),
    ONLINEMATCH_GET_VIP(DHMessage.PATH_ONLINEMATCH_GET_VIP_URL, DHMessage.METHOD_ONLINEMATCH_GET_VIP_POST, null),
    GAMEONLINE_SET_LIVE(DHMessage.PATH_GAMEONLINE_SET_LIVE_URL, DHMessage.METHOD_GAMEONLINE_SET_LIVE_POST, null),

    GAME_ONLINE_CANCELAUTOSTATUS(DHMessage.GAME_ONLINE_CANCELAUTOSTATUS, DHMessage.GAME_ONLINE_CANCELAUTOSTATUS_GET, null),

    GAME_ONLINE_UPDATEDARTS(DHMessage.GAME_ONLINE_UPDATEDARTS, DHMessage.GAME_ONLINE_UPDATEDARTS_POST, null),
    GAME_ONLINE_GETDARTDATA(DHMessage.GAME_ONLINE_GETDARTDATA, DHMessage.GAME_ONLINE_GETDARTDATA_GET, null),
    //lucky
    LUCKYDISC_PRIZES_GET(DHMessage.LUCKYDISC_PRIZES_URL,DHMessage.LUCKYDISC_PRIZES_GET,null),
    LUCKYDISC_DATA(DHMessage.LUCKYDISC_DATA_URL,DHMessage.LUCKYDISC_DATA_GET,null),
    LUCKYDISC_DATA_STORE(DHMessage.LUCKYDISC_STORE_URL,DHMessage.LUCKYDISC_STORE_GET,null),
    LUCKYDISC_AWARD_SORT_STORE(DHMessage.LUCKYDISC_AWARD_SORT_URL,DHMessage.LUCKYDISC_AWARD_SORT_GET,null),
    LUCKYDISC_EDIT_AWARD(DHMessage.LUCKYDISC_EDIT_AWARD_URL, DHMessage.LUCKYDISC_EDIT_AWARD_GET, null),
    LUCKYDISC_DEL_AWARD(DHMessage.LUCKYDISC_DEL_AWARD_URL, DHMessage.LUCKYDISC_DEL_AWARD_GET, null),
    LUCKYDISC_INIT(DHMessage.PATH_LUCKYDISC_INIT_URL, DHMessage.METHOD_LUCKYDISC_INIT_GET, null),
    LUCKYDISC_PAY_URL(DHMessage.PATH_LUCKYDISC_PAYING_URL, DHMessage.METHOD_LUCKYDISC_PAYING_URL_POST, null),
    LUCKYDISC_SCORE_UP(DHMessage.PATH_LUCKY_UP_SCORE_URL, DHMessage.METHOD_LUCKY_UP_SCORE_POST, null),

    ///////wgw
    OSS_GET_TOKEN(DHMessage.PATH_UPLOD_VIDEO_TOKEN_URL, DHMessage.METHOD_UPLOD_VIDEO_TOKEN_POST, null),
    UPLOAD_VIDEO_DONE(DHMessage.PATH_UPLOAD_VIDEO_DONE_URL, DHMessage.METHOD_UPLOAD_VIDEO_DONE_POST, null);

    private String mApi; // api path
    private String mMethod; // post or get
    private Class<?> mClass; // javabeen used to parse json

    private EnumTasks(String api, String method, Class<?> cla) {
        this.mApi = api;
        this.mMethod = method;
        this.mClass = cla;
    }

    /**
     * 创建Http 消息                              76
     * C:\Users\Administrator\AppData\Local\Android\Sdk
     *
     * @param params
     * @return
     */
    public void newTaskMessage(Context context, HashMap<String, String> params, ApiCallBack callBack) {
        H8HttpMessage h8HttpMsg = H8HttpMessage.createForHttp(mApi, params, mMethod, shouldHttpsRequst(mApi));
        IMNWManager.getInstance().sendMessage(context, h8HttpMsg, callBack);
    }

    /**
     * 创建普通Http 消息
     *
     * @param params
     * @return
     */
    public void newTaskMessageNor(Context context, HashMap<String, String> params, boolean isHttps,
                                  ApiCallBack callBack) {
        H8HttpMessage h8HttpMsg = H8HttpMessage.createForHttpDefeat(mApi,
                params, mMethod, isHttps);
        IMNWManager.getInstance().sendMessage(context, h8HttpMsg, callBack);
    }

    public void newTaskMessageNor(Context context, HashMap<String, String> params,
                                  ApiCallBack callBack) {
        newTaskMessageNor(context, params, false, callBack);
    }

    /**
     * 创建Http 文件上传消息
     *
     * @param apiParams
     * @return
     */
    public void newFileUplodTaskMessage(Context context, HashMap apiParams, ApiCallBack callBack) {
        H8FileUploadMessage h8HttpFileUploadMsg = H8FileUploadMessage.createForHttp(mApi, apiParams, mMethod);
        IMNWManager.getInstance().sendMessage(context, h8HttpFileUploadMsg, callBack);
    }

    /**
     * 判断是否应该使用Https的方式进行API访问
     *
     * @param path
     * @return
     */
    private boolean shouldHttpsRequst(String path) {
        if (TextUtils.equals(DHMessage.PATH__ACCOUNT_LOGIN_, path)
                || TextUtils.equals(DHMessage.PATH__ACCOUNT_REGISTER_, path)
                || TextUtils.equals(DHMessage.PATH__ACCOUNT_PSWDRESET_, path)
                || TextUtils.equals(DHMessage.PATH__ACCOUNT_GETOPENINFO_, path)
                || TextUtils.equals(DHMessage.PATH_ACCOUNT_WX_LOGIN, path)
                || TextUtils.equals(DHMessage.PATH_ACCOUNT_OPEN_REGISTER, path)
                || TextUtils.equals(DHMessage.PATH_ACCOUNT_OPENMOBCODE, path)
                || TextUtils.equals(DHMessage.PATH_ACCOUNT_OPEN_REGISTER_MOBILE, path)
                ) {
            return true;
        }
        return false;
    }
}
